# Add 'repo' label to any root file changes
repo:
- '*'

# Add '@domain/core' label to any change within the 'core' package
'@warehouse':
- warehouse/*

# Add 'test' label to any change to *.spec.js files within the source dir
test:
- **notebooks/**
